--Change all greek commands 'letter' to LaTeX '\letter'. Also, all greek UTF8 instances translate to plain english or to the corresponding LaTeX command

local map = {
    alpha   = ' \\alpha',
    ['α']   = ' \\alpha',
    Alpha   = ' A',
    ['Α']   = ' A',
    beta    = ' \\beta',
    ['β']   = ' \\beta',
    Beta    = ' B',
    ['Β']   = ' B',
    gamma   = ' \\gamma',
    ['γ']   = ' \\gamma',
    Gamma   = ' \\Gamma',
    ['Γ']   = ' \\Gamma',
    delta   = ' \\delta',
    ['δ']   = ' \\delta',
    Delta   = ' \\Delta',
    ['Δ']   = ' \\Delta',
    epsilon = ' \\varepsilon',
    ['ε']   = ' \\varepsilon',
    Epsilon = ' E',
    ['Ε']   = ' E',
    zeta    = ' \\zeta',
    ['ζ']   = ' \\zeta',
    Zeta    = ' Z',
    ['Ζ']   = ' Z',
    eta     = ' \\eta',
    ['η']   = ' \\eta',
    Eta     = ' H',
    ['Η']   = ' H',
    theta   = ' \\theta',
    ['θ']   = ' \\theta',
    Theta   = ' \\Theta',
    ['Θ']   = ' \\Theta',
    Iota    = ' I',
    ['Ι']   = ' I',
    kappa   = ' \\kappa',
    ['κ']   = ' \\kappa',
    Kappa   = ' K',
    ['Κ']   = ' K',
    lambda  = ' \\lambda',
    ['λ']   = ' \\lambda',
    Lambda  = ' \\Lambda',
    ['Λ']   = ' \\Lambda',
    mu      = ' \\mu',
    ['μ']   = ' \\mu',
    Mu      = ' M',
    ['Μ']   = ' M',
    nu      = ' \\nu',
    ['ν']   = ' \\nu',
    Nu      = ' N',
    ['Ν']   = ' N',
    xi      = ' \\xi',
    ['ξ']   = ' \\xi',
    Xi      = ' \\Xi',
    ['Ξ']   = ' \\Xi',
    omicron = ' o',
    ['ο']   = ' o',
    Omicron = ' O',
    ['Ο']   = ' O',
    pi      = ' \\pi',
    ['π']   = ' \\pi',
    Pi      = ' \\Pi',
    ['Π']   = ' \\Pi',
    rho     = ' \\varrho',
    ['ρ']   = ' \\varrho',
    Rho     = ' P',
    ['Ρ']   = ' P',
    sigma   = ' \\sigma',
    ['σ']   = ' \\sigma',
    Sigma   = ' \\Sigma',
    ['Σ']   = ' \\Sigma',
    tau     = ' \\tau',
    ['τ']   = ' \\tau',
    Tau     = ' T',
    ['Τ']   = ' T',
    upsilon = ' \\upsilon',
    ['υ']   = ' \\upsilon',
    Upsilon = ' \\Upsilon',
    ['Υ']   = ' \\Upsilon',
    phi     = ' \\phi',
    ['φ']   = ' \\phi',
    Phi     = ' \\Phi',
    ['Φ']   = ' \\Phi',
    chi     = ' \\chi',
    ['χ']   = ' \\chi',
    Chi     = ' X',
    ['Χ']   = ' X',
    psi     = ' \\psi',
    ['ψ']   = ' \\psi',
    Psi     = ' \\Psi',
    ['Ψ']   = ' \\Psi',
    omega   = ' \\omega',
    ['ω']   = ' \\omega',
    Omega   = ' \\Omega',
    ['Ω']   = ' \\Omega',
    
    --\begin{math}
    ['\\begin{math}'] = ' \\begin{math}',
    
    --Other miscellaneous characters.
    ['.']       = ' \\cdot',
}

local function characters(chrc)
    return map[chrc] or (' ' .. chrc)
end

return characters
